import { ApiProperty } from '@nestjs/swagger';
import { Document } from 'mongoose';

export class CreateUserDTO extends Document {
  @ApiProperty({
    description: 'First name of the user',
    required: true,
    type: String,
  })
  first_name: string;

  @ApiProperty({
    description: 'Last name of the user',
    required: true,
    type: String,
  })
  last_name: string;

  @ApiProperty({
    description: 'Email address of the user',
    required: true,
    type: String,
  })
  email: string;

  @ApiProperty({
    description: 'Country of the user, in capitalized alpha2 format. eg: IN',
    required: false,
    type: String,
  })
  country_alpha2?: string;

  @ApiProperty({
    description: 'Phone number of the user',
    required: false,
    type: String,
  })
  phone?: string;

  @ApiProperty({
    description: "Encrypted string of the user account's password",
    required: true,
    type: String,
  })
  encrypted_password: string;
}

export class User extends Document {
  @ApiProperty({
    description: 'ID of the user account (autogenerated)',
    required: false,
    type: String,
  })
  id?: string;

  @ApiProperty({
    description: 'First name of the user',
    required: true,
    type: String,
  })
  first_name: string;

  @ApiProperty({
    description: 'Last name of the user',
    required: true,
    type: String,
  })
  last_name: string;

  @ApiProperty({
    description: 'Email address of the user',
    required: true,
    type: String,
  })
  email: string;

  @ApiProperty({
    description: 'Country of the user, in upper-case alpha2 format. eg: IN',
    required: false,
    type: String,
  })
  country_alpha2?: string;

  @ApiProperty({
    description: 'Phone number of the user',
    required: false,
    type: String,
  })
  phone?: string;

  @ApiProperty({
    description: "Encrypted string of the user account's password",
    required: true,
    type: String,
  })
  encrypted_password: string;

  @ApiProperty({
    description: 'Creation date of the user account (autogenerated)',
    required: false,
    type: String,
  })
  created_date: Date;

  @ApiProperty({
    description: 'Whether user account is active',
    required: false,
    type: String,
  })
  is_active: boolean;
}
